export { default as MyContainer } from "./MyContainer/MyContainer";
export { default as Footer } from "./Footer/Footer";
export { default as Navbar } from "./Navbar/Navbar";
export { default as Hero } from "./Hero/Hero";
export { default as Logo } from "./Logo/Logo";
export { default as Main_1 } from "./Main_1/Main_1";
export { default as Main_2 } from "./Main_2/Main_2";
export { default as Main_3 } from "./Main_3/Main_3";
export { default as Email } from "./Email/Email";
